kubeovn/docs

- docs/guide/vpc.md
staticRoutes not in VpcNatGateway crd anymore
> doc: Update vpc.md

- docs/advance/vip.md
feature: add pod use vip to make ip static
> add pod use vip to make ip static

- docs/advance/with-ovn-ic.md
> add privileged parameter in docker/ctr run

- docs/advance/vpc-peering.en.md
- docs/advance/vpc-peering.md
1. fix create vpcPeerings code
2. add create Pods under the two subnets and test case
> fix: update vpc-peering doc

- docs/advance/cilium-networkpolicy.md
> optimise cilium policy doc

- docs/guide/qos.en.md
- docs/guide/qos.md
> remove htb qos temporally

- docs/start/underlay.md
> add known issues for underlay

- docs/guide/setup-options.en.md
- docs/guide/setup-options.md
- docs/guide/subnet.en.md
- docs/guide/subnet.md
> append doc for subnet spec enableLb and enableEcmp

- docs/reference/ovs-ovn-customized.en.md
- docs/reference/ovs-ovn-customized.md
> update OVS/OVN Customization

- .github/workflows/lint.yml
> debug lint

- docs/reference/kube-ovn-api.en.md
- docs/reference/kube-ovn-api.md
- mkdocs.yml
> add doc for kube-ovn crd

- docs/advance/security-group.en.md
- docs/advance/security-group.md
- docs/reference/kube-ovn-api.en.md
- docs/reference/kube-ovn-api.md
- mkdocs.yml
> add doc for security-group

- docs/advance/ovn-eip-fip-snat.en.md
- docs/advance/ovn-eip-fip-snat.md
- docs/advance/ovn-l3-ha-based-ecmp-with-bfd.en.md
- docs/advance/ovn-l3-ha-based-ecmp-with-bfd.md
- mkdocs.yml
> add ovn eip fip snat doc

- docs/advance/ovn-l3-ha-based-ecmp-with-bfd.en.md
- docs/advance/ovn-l3-ha-based-ecmp-with-bfd.md
> update ovn eip node-ext-gw type usage requirement

- docs/guide/loadbalancer-service.md
> fix spelling mistakes

- docs/guide/vpc.en.md
- docs/guide/vpc.md
> update vpc.md for custom vpc image configuration

- .github/workflows/lint.yml
- docs/advance/vpc-dns.md
- docs/guide/vpc.en.md
- docs/guide/vpc.md
> vpc-nat-gw 镜像单独维护相关文档变更

- docs/guide/vpc.en.md
- docs/guide/vpc.md
#https://github.com/kubeovn/kube-ovn/issues/2599
> fix: nad lost ipam config

- docs/reference/dev-env.en.md
- docs/reference/dev-env.md
> update e2e tests commands

- docs/advance/ovn-remote-port-mirroring.en.md
- docs/advance/ovn-remote-port-mirroring.md
- mkdocs.yml
> add document for OVN remote port mirroring

- docs/reference/dev-env.en.md
- docs/reference/dev-env.md
> update e2e iptables nat gw

- docs/start/one-step-install.en.md
- docs/start/one-step-install.md
> add document for helm install

- docs/guide/qos.md
- docs/ops/kubectl-ko.en.md
- docs/ops/kubectl-ko.md
> update document for ko plugin

- docs/guide/vpc.en.md
- docs/guide/vpc.md
> vpc nat gw has no staticRoutes

- docs/guide/subnet.en.md
- docs/guide/subnet.md
- docs/guide/vpc.en.md
- docs/guide/vpc.md
> multiple route tables

- docs/start/underlay.en.md
- docs/start/underlay.md
> support disable vlan ip arp conflict detection

- docs/guide/vpc-qos.en.md
- docs/guide/vpc-qos.md
- docs/guide/vpc.en.md
- docs/guide/vpc.md
feat: https://github.com/kubeovn/kube-ovn/pull/2725
> docs: multiple external netowrk

- docs/advance/vip.en.md
- docs/advance/vip.md
> update vip usage

- docs/reference/feature-stage.en.md
- docs/reference/feature-stage.md
> 对中文的功能特性相关文档进行跳转优化

- docs/start/underlay.en.md
- docs/start/underlay.md
> update underlay document

- docs/advance/accelerate-intra-node-tcp-with-ebpf.en.md
- docs/advance/cilium-hubble-observe.en.md
- docs/advance/cilium-networkpolicy.en.md
- mkdocs.yml
> docs: add English-language documentation

- docs/guide/ippool.en.md
- docs/guide/ippool.md
- docs/guide/subnet.en.md
- docs/guide/subnet.md
- mkdocs.yml
> add document for ippool

- docs/ops/kubectl-ko.en.md
- docs/ops/kubectl-ko.md
> kubectl ko perf diagnose

- docs/advance/vip.en.md
- docs/advance/vip.md
about the pr https://github.com/kubeovn/kube-ovn/pull/3053
> add keep vip in document

- docs/advance/ovn-eip-fip-snat.en.md
- docs/advance/ovn-eip-fip-snat.md
- docs/advance/ovn-l3-ha-based-ecmp-with-bfd.en.md
- docs/advance/ovn-l3-ha-based-ecmp-with-bfd.md
> 简化 oeip 类型,支持 lrp 类型被 nat 复用

- docs/guide/ippool.en.md
- mkdocs.yml
> Ippool en fix

- docs/advance/vip.md
- docs/guide/static-ip-mac.en.md
- docs/guide/static-ip-mac.md
> update vip and sts use static up

- docs/guide/subnet.en.md
- docs/guide/subnet.md
> add multcast snoop

- docs/reference/dev-env.en.md
- docs/reference/dev-env.md
> use go install instead of go get to install plugins

- docs/ops/kubectl-ko.en.md
- docs/ops/kubectl-ko.md
> update kubectl-ko usage

- docs/guide/subnet.en.md
- docs/guide/subnet.md
> add allowSameSubnetTraffic docs

- docs/guide/mirror.en.md
- docs/guide/mirror.md
> add performance test for mirror

- docs/advance/ovn-eip-fip-snat.en.md
- docs/advance/ovn-eip-fip-snat.md
添加自定义vpc额外公网网卡功能介绍，添加英文文档
https://github.com/kubeovn/kube-ovn/pull/3264
> 添加自定义vpc额外公网网卡功能介绍

- docs/guide/subnet.en.md
- docs/guide/subnet.md
> add mtu for subnet

- docs/advance/ovn-ipsec.en.md
- docs/advance/ovn-ipsec.md
- docs/guide/subnet.en.md
- docs/guide/subnet.md
> add limitation of centralized gateway subnet

- docs/advance/with-bgp.en.md
Add Bgp Advance Options
- passivemode
> Add Bgp Advance Options

- docs/reference/kube-ovn-api.en.md
- docs/reference/kube-ovn-api.md
> update ovn eip dnat snat api

- docs/advance/ovn-eip-fip-snat.en.md
- docs/advance/ovn-eip-fip-snat.md
> update ovn eip fip dnat snat in 1.12

- docs/guide/vpc.md
> v1.10 创建 DNAT 规则yaml缺少”:“

- docs/reference/kube-ovn-api.en.md
- docs/reference/kube-ovn-api.md
> update vip api

- mkdocs.yml
fix https://github.com/kubeovn/docs/issues/153
> modify copyright

- docs/guide/subnet.en.md
- docs/guide/subnet.md
> update subnet bind workload

- docs/advance/offload-mellanox.en.md
- docs/advance/offload-mellanox.md
> update: mellanox offload usage example

- docs/start/one-step-install.en.md
- docs/start/one-step-install.md
> fix ha chart install MASTER_NODES parameter error

- docs/advance/security-group.en.md
- docs/advance/security-group.md
> diff sg  with port-security

- docs/reference/dev-env.en.md
This tool is needed while building and not documented
> feat(references): add gofumpt install

- docs/guide/networkpolicy-log.en.md
- docs/guide/networkpolicy-log.md
- docs/reference/annotations.en.md
- docs/reference/annotations.md
> add acl log document

- docs/advance/with-cilium.en.md
- docs/advance/with-cilium.md
> fix outdated url

- docs/guide/vpc.md
- docs/reference/kube-ovn-api.md
> add translation for default subnet

- docs/guide/prometheus-grafana.md
> Correct incorrect Chinese characters

- docs/advance/with-cilium.en.md
Fixes documentation problem for https://github.com/kubeovn/kube-ovn/issues/4314
> Documentation for NAT GW + Cilium SIP

- docs/advance/security-group.en.md
@oilbeater Hi, this PR references https://github.com/kubeovn/kube-ovn/issues/4652
> feat(doc): clarify port_security

- mkdocs.yml
> lost guide/ip doc

- docs/advance/vpc-egress-gateway.en.md
- docs/advance/vpc-egress-gateway.md
- mkdocs.yml
> add document for vpc egress gateway

- docs/advance/ovn-eip-fip-snat.en.md
- docs/advance/ovn-eip-fip-snat.md
> fix: addExternalSubnets -> extraExternalSubnets

- docs/guide/loadbalancer-service.en.md
- docs/guide/loadbalancer-service.md
- docs/guide/vpc.en.md
- docs/guide/vpc.md
> add node selector for lb svc gateway

- docs/advance/vpc-egress-gateway.en.md
- docs/advance/vpc-egress-gateway.md
- docs/reference/feature-stage.en.md
- docs/reference/feature-stage.md
> update documents for vpc egress gateway

- docs/guide/vpc.en.md
- docs/guide/vpc.md
Fix the incorrect **v4ip** field value in the **Fixed EIP address assignment**
> Modify the value of the EIP v4ip field

- docs/advance/with-cilium.en.md
> feat(cilium): cilium now supports disabling SIP

- docs/start/talos-install.en.md
- docs/start/talos-install.md
- mkdocs.yml
> add installation guide for Talos

- docs/start/one-step-install.en.md
- docs/start/one-step-install.md
- docs/start/prepare.en.md
- docs/start/prepare.md
- docs/start/talos-install.en.md
- docs/start/talos-install.md
- mkdocs.yml
> fix chart installation instructions

- docs/start/one-step-install.en.md
- docs/start/one-step-install.md
> Enhance upgrade instructions for  installation

- docs/index.en.md
- docs/index.md
> add cni selection

- .github/workflows/lint.yml
- docs/advance/with-ovn-ic.en.md
- docs/advance/with-ovn-ic.md
> add limitation for ovn-ic

- docs/vpc/vpc-egress-gateway.en.md
- docs/vpc/vpc-egress-gateway.md
> update document about vpc egress gateway

- docs/vpc/vpc-egress-gateway.en.md
- docs/vpc/vpc-egress-gateway.md
Signed-off-by: Mengxin Liu <liumengxinfly@gmail.com>
> update VPC Egress Gateway documentation to clarify features and limitations

- docs/start/talos-install.en.md
- docs/start/talos-install.md
> update documents about Talos installation

- docs/start/prepare.en.md
- docs/start/prepare.md
> update documents about prerequisites

- docs/advance/accelerate-intra-node-tcp-with-ebpf.en.md
- docs/advance/accelerate-intra-node-tcp-with-ebpf.md
- docs/start/prepare.en.md
- docs/start/prepare.md
- docs/vpc/vpc-peering.en.md
- docs/vpc/vpc-peering.md
> fix format and test action

- docs/start/one-step-install.en.md
- docs/start/one-step-install.md
- docs/start/uninstall.en.md
- docs/start/uninstall.md
> add helm uninstall

- docs/reference/kube-ovn-api.en.md
- docs/reference/kube-ovn-api.md
- docs/start/underlay.en.md
- docs/start/underlay.md
> Add providernetwork with nodeselector

- docs/vpc/vpc-internal-dns.en.md
- docs/vpc/vpc-internal-dns.md
> add notes for vpc-dns

- docs/advance/multi-nic.en.md
- docs/advance/multi-nic.md
> add multus compatibility issues

- docs/kubevirt/vm-clone.en.md
- docs/kubevirt/vm-clone.md
- mkdocs.yml
> add vm clone guide

- docs/advance/vip.en.md
- docs/vpc/vpc-internal-lb.en.md
> fix(doc): notes in vpc-internal-lb

- docs/guide/subnet.en.md
- docs/guide/subnet.md
- docs/vpc/security-group.en.md
- docs/vpc/security-group.md
> add warning about acls

- docs/guide/static-ip-mac.en.md
- docs/guide/static-ip-mac.md
- docs/kubevirt/static-ip.en.md
- docs/kubevirt/static-ip.md
- mkdocs.yml
> add annotations and links

- docs/kubevirt/static-ip.en.md
- docs/kubevirt/static-ip.md
> add instructions for changing VM IP addresses

- docs/start/production.en.md
- docs/start/production.md
- mkdocs.yml
> add production ready guides

- docs/advance/performance-tuning.en.md
- docs/advance/performance-tuning.md
- docs/ops/kubectl-ko.en.md
- docs/ops/kubectl-ko.md
> remove ko tunning

- docs/reference/ovs-ovn-customized.en.md
- docs/reference/ovs-ovn-customized.md
> update ovs/ovn patches

- docs/advance/performance-tuning.en.md
- docs/advance/performance-tuning.md
> deprecate warning about stt

- docs/advance/egress-firewall.en.md
- docs/advance/egress-firewall.md
> add egress firewall

- docs/guide/networkpolicy-log.en.md
- docs/guide/networkpolicy-log.md
> fix networkpolicy log format

- docs/guide/subnet.en.md
- docs/guide/subnet.md
> limt gateway to subnet in default vpc

- docs/vpc/vpc.en.md
- docs/vpc/vpc.md
> add noeip gw
